### ISSUE TITLE
Gamepad state truncated when parsing JSON

### ISSUE THREAD

**Issue by barulicm** [gizmo-platform/firmware#1]
The last four button states (A, B, left shoulder, and right shoulder) do not work because the JSON object is getting truncated.

`cstateJSON` is configured with 384 bytes of memory pool, but the gamepad state message appears to take 491 bytes (according to `JsonDocument::memoryUsage()`). This results in keys towards the end of the message being omitted and the buttons associated with those keys never report being pressed.

**Comment by the-maldridge** [comment]
Closing as obsolete because we now use a version of ArduinoJSON with dynamic memory.
