### ISSUE TITLE
Shoulder buttons  do not reflect actual state.

### ISSUE THREAD

**Issue by the-maldridge** [gizmo-platform/firmware#2]
Shoulder buttons don't reflect the actual state of the shoulder buttons.  The state is correct in the MQTT frames, which strongly implies that the values are getting lost once they're on the board itself either in the system processor or that the student support library (this repo) isn't returning the values anymore.

**Comment by the-maldridge** [comment]
@Tomalaya suggested this is likely due to some static memory allocation issues in the json parser.  Since we're on an old version that has been obsoleted, the first step is to upgrade the json parser and see if the issue re-occurs.

**Comment by Tomalaya** [comment]
I did a quick test, upping the static document size in gizmo-fw.ino from 384 to 512, and my Shoulder Buttons worked!

Changed 
StaticJsonDocument<384> cstateJSON;
to
StaticJsonDocument<512> cstateJSON;

StaticJsonDocument docs in ArduinoJSON state anything less than 1K is still considered small document, so this could be a quick stopgap fix even without upgrading the parser

**Comment by the-maldridge** [comment]
Resolved by 9f04f23.
